baseurl = "http://avthart.github.io/"
languageCode = "en-us"
title = "avthart.io"
theme = "hyde"
copyright = "Albert van 't Hart"

[Author]
	name = "Albert van 't Hart"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[Params]
	description = "code by Albert van 't Hart"
	github = "https://github.com/avthart"	
	linkedin = "https://nl.linkedin.com/in/albertvanthart"